regions:
  - global
  - us-east-2

blocklist:
  - "551379999285" # production

accounts:
  "183295408236": # aws-nuke-account
    resource-types: 
      include:
        - S3Bucket
        - SageMakerNotebookInstance 
